"""added active column to places table

Revision ID: 328bf90ff683
Revises: f89d36297165
Create Date: 2021-09-06 16:26:49.659432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '328bf90ff683'
down_revision = 'f89d36297165'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('places', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('places', 'active')
    # ### end Alembic commands ###
