"""

Revision ID: 4b804408e5f6
Revises: 328bf90ff683
Create Date: 2021-11-14 17:32:13.352014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b804408e5f6'
down_revision = '328bf90ff683'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('alias', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'alias')
    # ### end Alembic commands ###
