"""Adding column active

Revision ID: aa154bb680a7
Revises: 3510860323b7
Create Date: 2021-09-06 13:39:34.379972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa154bb680a7'
down_revision = '3510860323b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('places', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('places', 'active')
    # ### end Alembic commands ###
